import Head from 'next/head'
import Header from '../components/Header'

import Sidebar from '../components/Sidebar.jsx'
import LoginPage from '../components/LoginPage'
import Feed from '../components/Feed.jsx'
import Widgets from '../components/Widgets.jsx'

import { getSession } from 'next-auth/react'
import { collection, orderBy, query, getDocs } from 'firebase/firestore'
import { db } from '../firebase'

export default function Home({ session, posts, users, stories }) {

  if (!session) return <LoginPage />;

  return (
    <div className='h-screen bg-gray-100 overflow-hidden'> 
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className='flex'>
        {/* Sidebar */}
        <Sidebar />
          
        {/* Feed */}
        <Feed posts={posts} stories={stories} />

        {/* Widgets */}
        <Widgets users={users} />

      </main>

    </div>
  )
}

export async function getServerSideProps(context) {
  
  const session = await getSession(context)

  const postRef = collection(db, 'posts')
  const posts = await getDocs(query(postRef, orderBy("timestamp", "desc")))
  const docs = posts.docs.map(doc => { 
    const { timestamp, ...rest } = doc.data()
    return {
    id: doc.id,
    timestamp: timestamp?.toDate(),
    ...rest
    }
  })

  const people = await fetch('https://randomuser.me/api/?results=10').then(async res => await res.json())

  const stories = await fetch('https://reqres.in/api/users?per_page=4').then(async res => await res.json())


  return {
    props: {
      session,
      posts: [],
      users: people.results.map(p => ({ id: p.id.value, name: `${p.name.first} ${p.name.last}`, src: p.picture.thumbnail })),
      stories: stories.data.map(story => ({ id: story.id, src: story.avatar, profile: story.avatar }))
    }
  }
}

